version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: sts
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-sts}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-sTs@1535}
      POSTGRES_DB: ${POSTGRES_DB:-sts_db}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-sts} -d ${POSTGRES_DB:-sts_db}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
    driver: local


